#!/bin/bash

# Stop and remove existing containers
docker stop connect kafka zookeeper
docker rm connect kafka zookeeper

curl -i -X DELETE http://localhost:8083/connectors/stream1

# Run Zookeeper container
docker run -it -d --name zookeeper -p 2181:2181 -p 2888:2888 -p 3888:3888 quay.io/debezium/zookeeper:2.5

# Run Kafka container
docker run -it -d --name kafka -p 9092:9092 --link zookeeper:zookeeper quay.io/debezium/kafka:2.5

# Run Connect container
docker run -it -d --name connect -p 8083:8083 -e GROUP_ID=1 -e CONFIG_STORAGE_TOPIC=my_connect_configs -e OFFSET_STORAGE_TOPIC=my_connect_offsets -e STATUS_STORAGE_TOPIC=my_connect_statuses --link kafka:kafka -e MYSQL_HOST=13.200.153.16 -e MYSQL_PORT=3306 -e MYSQL_USER=datasync_readonly_prod -e MYSQL_PASSWORD=vFDxHHABpQYITvg quay.io/debezium/connect:2.5

# Create the connector
curl -i -X POST -H "Accept:application/json" -H "Content-Type:application/json" localhost:8083/connectors/ -d '{ "name": "stream1", "config": { "connector.class": "io.debezium.connector.mysql.MySqlConnector", "tasks.max": "1", "database.hostname": "13.200.153.16", "database.port": "3306", "database.user": "datasync_readonly_prod", "database.password": "vFDxHHABpQYITvg", "database.server.id": "10001", "topic.prefix": "datasync", "database.include.list": "_74482e142a30d6f9", "table.include.list":"_74482e142a30d6f9.tabVehicle Inspection Assignment","schema.history.internal.kafka.bootstrap.servers": "kafka:9092","schema.history.internal.kafka.topic": "schemahistory._74482e142a30d6f9","connector.adapter": "mariadb"} }'

